# Tested with golangci-lint ver. 2.x
version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    - asciicheck        # checks for non-ASCII identifiers
    - bidichk           # checks for dangerous unicode sequences (security)
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - errname           # checks error naming conventions
    - exhaustive
    - gocheckcompilerdirectives  # validates go compiler directives
    - goconst
    - goprintffuncname
    - staticcheck
    - ineffassign
    - makezero          # finds slice declarations with non-zero initial length
    - misspell
    - reassign          # checks package variable reassignment
    - unconvert
    - unused
    - whitespace

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: "logging is allowed only by logutils.Log"
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - vendor/
      - .github/
    rules:
      - path: _test\.go
        linters:
          - gosec
          - dupl
          - goconst

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/intel/bond-cni

