issues:
  exclude-rules:
    - linters:
        - revive
      text: "don't use ALL_CAPS in Go names; use CamelCase"
    - linters:
        - revive
      text: " and that stutters;"

linters:
  enable:
    - contextcheck
    - durationcheck
    - gci
    - ginkgolinter
    - gocritic
    - gofumpt
    - gosimple
    - ineffassign
    - misspell
    - nonamedreturns
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
  disable:
    - errcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/containernetworking)

run:
  skip-dirs:
    - vendor
