name: build

on: ["push", "pull_request"]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v9
        with:
          args: -v

  build:
    name: build
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: make build-bin

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    name: unit-test
    container:
      image: golang:1.25
      options: --privileged
    steps:
      - uses: actions/checkout@v6

      - name: Go test with coverage
        run: go test -race -covermode=atomic -coverprofile=profile.out ./... -v --ginkgo.v

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: profile.out
          format: golang
