name: Image push release
on:
  push:
    tags:
      - v*
env:
  image-push-owner: 'k8snetworkplumbingwg'
jobs:
  push:
    name: Image push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: ${{ github.repository_owner == env.image-push-owner }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=false

      - name: Push container image
        if: ${{ github.repository_owner == env.image-push-owner }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:stable
            ${{ steps.docker_meta.outputs.tags }}
          file: images/Dockerfile
